### PR TITLE
Return default values if schema changes have not been completed

### LINKED ISSUE #922: Unexpected exception when using incremental repairs
When using incremental repairs, under certain situations, ecChronos queries new tables before they have been fully created.

This can be observed in the ecChronos log:
`2025-03-27T07:35:46.780+01:00 ERROR 340933 --- [pairScheduler-0] c.e.b.c.e.c.repair.RepairSchedulerImpl   : Unexpected error during schedule change of foo.bar`
`javax.management.RuntimeMBeanException: java.lang.IllegalArgumentException: Unknown keyspace/cf pair (foo.bar)`

The Cassandra log's timestamp for the init of the table:
`INFO  [Native-Transport-Requests-1] 2025-03-27 07:35:50,748 ColumnFamilyStore.java:484 - Initializing foo.bar`

Most likely a sync problem...

### PR DESCRIPTION
**Pull request by jwaeab**
Closes #922

### CODE REVIEW

File: core/src/main/java/com/ericsson/bss/cassandra/ecchronos/core/JmxProxyFactoryImpl.java [hunk 1]
```diff
@@ -303,14 +316,20 @@ public double getPercentRepaired(final TableReference tableReference)
...
                    | MalformedObjectNameException e)
             {
                 LOG.error("Unable to retrieve disk space usage for {}", tableReference, e);
             }
+            catch (RuntimeMBeanException
+                   | InstanceNotFoundException e)
+            {
+                // This exception can occur when a table is about to be changed, but has not finished doing so
+                // before we try to fetch data from it. Just return the default value for the time being.
+                LOG.warn("Unable to retrieve disk space usage for {} (bean not yet ready)", tableReference);
```
Comment (tommystendahl) [inline core/src/main/java/com/ericsson/bss/cassandra/ecchronos/core/JmxProxyFactoryImpl.java:331]: "retrieve disk space usage"? Maybe something like "Percent Repaired in by incremental repair"

**Review by tommystendahl — CHANGES_REQUESTED** [review]
