### PR TITLE
Fix priority for repair jobs

### LINKED ISSUE #515: Prioritization of scheduled jobs is not correct while Cassandra nodes are considered down
Prioritizaion of TableRepairJob and tasks it creates (RepairGroup) is not correct.
The real priority of TableRepairJob is based on vnodes that will not be repaired because some of the replicas are down:
See calculation of repairedAt and excluding [here](https://github.com/Ericsson/ecchronos/blob/9037f507e04a3247d31b990d848a55ea6d4a047d/core/src/main/java/com/ericsson/bss/cassandra/ecchronos/core/repair/state/RepairStateImpl.java#L124)

More or less what happens is that, we calculate repairedAt based on all vnodes and replicas, later on we exclude some vnodes because replicas are down. The repairedAt is used for calculating realPriority, i.e the priority might be higher for jobs than intended. The consequences of this is too high priority in lock_priority table which slows down repairs because ecchronos won't even try to lock if the local priority is lower than what is in that table.

I think a solution to this would be to calculate the priority based on what the job can repair.

### PR DESCRIPTION
**Pull request by masokol**
Closes #515

### CODE REVIEW

**Review by tommystendahl — APPROVED** [review]

File: core/src/test/java/com/ericsson/bss/cassandra/ecchronos/core/repair/TestTableRepairJob.java [hunk 1]
```diff
@@ -477,6 +495,7 @@ public void testLastSuccessfulRunIsBasedOnRepairHistory()
         // Repair has been completed
         doReturn(lastRepairedAtAfterRepair).when(myRepairStateSnapshot).lastRepairedAt();
         doReturn(false).when(myRepairStateSnapshot).canRepair();
```
Comment (masokol) [inline core/src/test/java/com/ericsson/bss/cassandra/ecchronos/core/repair/TestTableRepairJob.java:497]: Maybe add some more tests for the priority method.

**Review by itskarlsson — APPROVED** [review]
