### PR TITLE
Codestyle fixes for core

### LINKED ISSUE #317: Align code to follow checkstyle
Checkstyle was added as part of #298.
Code should be aligned so we comply with it, once all of the code is aligned the ignoring of errors/warnings from checkstyle should be removed.

i.e remove this line from pom.xml
`<failOnViolation>false</failOnViolation>`

### PR DESCRIPTION
**Pull request by jwaeab**
Closes #317

### CODE REVIEW

File: core/src/main/java/com/ericsson/bss/cassandra/ecchronos/core/utils/package-info.java [hunk 1]
```diff
@@ -0,0 +1,19 @@
+/*
+ * Copyright 2020 Telefonaktiebolaget LM Ericsson
```
Comment (masokol) [inline core/src/main/java/com/ericsson/bss/cassandra/ecchronos/core/utils/package-info.java:2]: Copyright 2022

File: core/src/main/java/com/ericsson/bss/cassandra/ecchronos/core/repair/state/package-info.java [hunk 2]
```diff
@@ -0,0 +1,19 @@
+/*
+ * Copyright 2018 Telefonaktiebolaget LM Ericsson
```
Comment (masokol) [inline core/src/main/java/com/ericsson/bss/cassandra/ecchronos/core/repair/state/package-info.java:2]: Copyright 2022

File: core/src/main/java/com/ericsson/bss/cassandra/ecchronos/core/repair/package-info.java [hunk 3]
```diff
@@ -0,0 +1,19 @@
+/*
+ * Copyright 2018 Telefonaktiebolaget LM Ericsson
```
Comment (masokol) [inline core/src/main/java/com/ericsson/bss/cassandra/ecchronos/core/repair/package-info.java:2]: Copyright 2022

File: core/src/main/java/com/ericsson/bss/cassandra/ecchronos/core/package-info.java [hunk 4]
```diff
@@ -0,0 +1,18 @@
+/*
+ * Copyright 2019 Telefonaktiebolaget LM Ericsson
```
Comment (masokol) [inline core/src/main/java/com/ericsson/bss/cassandra/ecchronos/core/package-info.java:2]: Copyright 2022

File: core/src/main/java/com/ericsson/bss/cassandra/ecchronos/core/exceptions/package-info.java [hunk 5]
```diff
@@ -0,0 +1,18 @@
+/*
+ * Copyright 2018 Telefonaktiebolaget LM Ericsson
```
Comment (masokol) [inline core/src/main/java/com/ericsson/bss/cassandra/ecchronos/core/exceptions/package-info.java:2]: Copyright 2022

File: core/src/main/java/com/ericsson/bss/cassandra/ecchronos/core/metrics/package-info.java [hunk 6]
```diff
@@ -0,0 +1,18 @@
+/*
+ * Copyright 2019 Telefonaktiebolaget LM Ericsson
```
Comment (masokol) [inline core/src/main/java/com/ericsson/bss/cassandra/ecchronos/core/metrics/package-info.java:2]: Copyright 2022

File: core/src/main/java/com/ericsson/bss/cassandra/ecchronos/core/metrics/TableMetricHolder.java [hunk 7]
```diff
@@ -106,33 +117,57 @@ else if (repairedRanges == 0)
...
     public void succeededRepairTask()
     {
         myRepairSucceededAttempts.get().mark();
     }
 
-    public void repairTiming(long timeTaken, TimeUnit timeUnit, boolean successful)
+    /**
+     * Set repair timing.
+     *
+     * @param timeTaken Time token
```
Comment (itskarlsson) [inline core/src/main/java/com/ericsson/bss/cassandra/ecchronos/core/metrics/TableMetricHolder.java:166]: time taken

File: core/src/main/java/com/ericsson/bss/cassandra/ecchronos/core/repair/DefaultRepairConfigurationProvider.java [hunk 8]
```diff
@@ -89,8 +94,13 @@ private DefaultRepairConfigurationProvider(Builder builder)
         }
     }
 
+    /**
+     * On keyspace created.
```
Comment (itskarlsson) [inline core/src/main/java/com/ericsson/bss/cassandra/ecchronos/core/repair/DefaultRepairConfigurationProvider.java:98]: Called when Keyspace is created

File: core/src/main/java/com/ericsson/bss/cassandra/ecchronos/core/repair/DefaultRepairConfigurationProvider.java [hunk 9]
```diff
@@ -103,14 +113,26 @@ public void onKeyspaceCreated(KeyspaceMetadata keyspace)
         }
     }
 
+    /**
+     * On keyspace updated.
```
Comment (itskarlsson) [inline core/src/main/java/com/ericsson/bss/cassandra/ecchronos/core/repair/DefaultRepairConfigurationProvider.java:117]: Called when keyspace is updated

File: core/src/main/java/com/ericsson/bss/cassandra/ecchronos/core/repair/DefaultRepairConfigurationProvider.java [hunk 10]
```diff
@@ -103,14 +113,26 @@ public void onKeyspaceCreated(KeyspaceMetadata keyspace)
...
     @Override
-    public void onKeyspaceUpdated(KeyspaceMetadata current, KeyspaceMetadata previous)
+    public void onKeyspaceUpdated(final KeyspaceMetadata current,
+                                  final KeyspaceMetadata previous)
     {
         onKeyspaceCreated(current);
     }
 
+    /**
+     * On table created.
```
Comment (itskarlsson) [inline core/src/main/java/com/ericsson/bss/cassandra/ecchronos/core/repair/DefaultRepairConfigurationProvider.java:130]: Called when table is created

File: core/src/main/java/com/ericsson/bss/cassandra/ecchronos/core/repair/DefaultRepairConfigurationProvider.java [hunk 11]
```diff
@@ -120,8 +142,13 @@ public void onTableCreated(TableMetadata table)
         }
     }
 
+    /**
+     * On table dropped.
```
Comment (itskarlsson) [inline core/src/main/java/com/ericsson/bss/cassandra/ecchronos/core/repair/DefaultRepairConfigurationProvider.java:146]: Called when table is dropped

File: core/src/main/java/com/ericsson/bss/cassandra/ecchronos/core/repair/DefaultRepairConfigurationProvider.java [hunk 12]
```diff
@@ -130,12 +157,21 @@ public void onTableDropped(TableMetadata table)
         }
     }
 
+    /**
+     * On table updated.
```
Comment (itskarlsson) [inline core/src/main/java/com/ericsson/bss/cassandra/ecchronos/core/repair/DefaultRepairConfigurationProvider.java:161]: Called when table is updated

File: core/src/main/java/com/ericsson/bss/cassandra/ecchronos/core/repair/DefaultRepairConfigurationProvider.java [hunk 13]
```diff
@@ -181,100 +218,170 @@ private void updateConfiguration(TableReference tableReference, TableMetadata ta
...
+                && "org.apache.cassandra.db.compaction.TimeWindowCompactionStrategy".equals(compaction.get("class"));
     }
 
     public static Builder newBuilder()
     {
         return new Builder();
     }
 
+    /**
+     * On keyspace dropped.
```
Comment (itskarlsson) [inline core/src/main/java/com/ericsson/bss/cassandra/ecchronos/core/repair/DefaultRepairConfigurationProvider.java:244]: Called when keyspace is dropped

File: core/src/main/java/com/ericsson/bss/cassandra/ecchronos/core/repair/DefaultRepairConfigurationProvider.java [hunk 14]
```diff
@@ -181,100 +218,170 @@ private void updateConfiguration(TableReference tableReference, TableMetadata ta
...
+     */
     @Override
-    public void onKeyspaceDropped(KeyspaceMetadata keyspace)
+    public void onKeyspaceDropped(final KeyspaceMetadata keyspace)
     {
         // NOOP
     }
 
+    /**
+     * On user defined type created.
```
Comment (itskarlsson) [inline core/src/main/java/com/ericsson/bss/cassandra/ecchronos/core/repair/DefaultRepairConfigurationProvider.java:255]: Called when user defined types are created

File: core/src/main/java/com/ericsson/bss/cassandra/ecchronos/core/repair/DefaultRepairConfigurationProvider.java [hunk 15]
```diff
@@ -181,100 +218,170 @@ private void updateConfiguration(TableReference tableReference, TableMetadata ta
...
+     */
     @Override
-    public void onUserDefinedTypeCreated(UserDefinedType type)
+    public void onUserDefinedTypeCreated(final UserDefinedType type)
     {
         // NOOP
     }
 
+    /**
+     * On user defined type dropped.
```
Comment (itskarlsson) [inline core/src/main/java/com/ericsson/bss/cassandra/ecchronos/core/repair/DefaultRepairConfigurationProvider.java:265]: Called when user defined types are dropped

File: core/src/main/java/com/ericsson/bss/cassandra/ecchronos/core/repair/DefaultRepairConfigurationProvider.java [hunk 16]
```diff
@@ -181,100 +218,170 @@ private void updateConfiguration(TableReference tableReference, TableMetadata ta
...
+     */
     @Override
-    public void onUserDefinedTypeDropped(UserDefinedType type)
+    public void onUserDefinedTypeDropped(final UserDefinedType type)
     {
         // NOOP
     }
 
+    /**
+     * On user defined type updated.
```
Comment (itskarlsson) [inline core/src/main/java/com/ericsson/bss/cassandra/ecchronos/core/repair/DefaultRepairConfigurationProvider.java:276]: Called when user defined types are updated

File: core/src/main/java/com/ericsson/bss/cassandra/ecchronos/core/repair/DefaultRepairConfigurationProvider.java [hunk 17]
```diff
@@ -181,100 +218,170 @@ private void updateConfiguration(TableReference tableReference, TableMetadata ta
...
+     */
     @Override
-    public void onUserDefinedTypeUpdated(UserDefinedType current, UserDefinedType previous)
+    public void onUserDefinedTypeUpdated(final UserDefinedType current, final UserDefinedType previous)
     {
         // NOOP
     }
 
+    /**
+     * On function created.
```
Comment (itskarlsson) [inline core/src/main/java/com/ericsson/bss/cassandra/ecchronos/core/repair/DefaultRepairConfigurationProvider.java:288]: Called when functions are created

File: core/src/main/java/com/ericsson/bss/cassandra/ecchronos/core/repair/DefaultRepairConfigurationProvider.java [hunk 18]
```diff
@@ -181,100 +218,170 @@ private void updateConfiguration(TableReference tableReference, TableMetadata ta
...
+     */
     @Override
-    public void onFunctionCreated(FunctionMetadata function)
+    public void onFunctionCreated(final FunctionMetadata function)
     {
         // NOOP
     }
 
+    /**
+     * On function dropped.
```
Comment (itskarlsson) [inline core/src/main/java/com/ericsson/bss/cassandra/ecchronos/core/repair/DefaultRepairConfigurationProvider.java:299]: Called when functions are dropped

File: core/src/main/java/com/ericsson/bss/cassandra/ecchronos/core/repair/DefaultRepairConfigurationProvider.java [hunk 19]
```diff
@@ -181,100 +218,170 @@ private void updateConfiguration(TableReference tableReference, TableMetadata ta
...
+     */
     @Override
-    public void onFunctionDropped(FunctionMetadata function)
+    public void onFunctionDropped(final FunctionMetadata function)
     {
         // NOOP
     }
 
+    /**
+     * On function updated.
```
Comment (itskarlsson) [inline core/src/main/java/com/ericsson/bss/cassandra/ecchronos/core/repair/DefaultRepairConfigurationProvider.java:310]: Called when functions are updated

File: core/src/main/java/com/ericsson/bss/cassandra/ecchronos/core/repair/DefaultRepairConfigurationProvider.java [hunk 20]
```diff
@@ -181,100 +218,170 @@ private void updateConfiguration(TableReference tableReference, TableMetadata ta
...
+     */
     @Override
-    public void onFunctionUpdated(FunctionMetadata current, FunctionMetadata previous)
+    public void onFunctionUpdated(final FunctionMetadata current, final FunctionMetadata previous)
     {
         // NOOP
     }
 
+    /**
+     * On aggregate created.
```
Comment (itskarlsson) [inline core/src/main/java/com/ericsson/bss/cassandra/ecchronos/core/repair/DefaultRepairConfigurationProvider.java:322]: Called when aggregate is created

File: core/src/main/java/com/ericsson/bss/cassandra/ecchronos/core/repair/DefaultRepairConfigurationProvider.java [hunk 21]
```diff
@@ -181,100 +218,170 @@ private void updateConfiguration(TableReference tableReference, TableMetadata ta
...
+     */
     @Override
-    public void onAggregateCreated(AggregateMetadata aggregate)
+    public void onAggregateCreated(final AggregateMetadata aggregate)
     {
         // NOOP
     }
 
+    /**
+     * On aggregate updated.
```
Comment (itskarlsson) [inline core/src/main/java/com/ericsson/bss/cassandra/ecchronos/core/repair/DefaultRepairConfigurationProvider.java:333]: Called when aggregate is **dropped**

File: core/src/main/java/com/ericsson/bss/cassandra/ecchronos/core/repair/DefaultRepairConfigurationProvider.java [hunk 22]
```diff
@@ -181,100 +218,170 @@ private void updateConfiguration(TableReference tableReference, TableMetadata ta
...
+     */
     @Override
-    public void onAggregateDropped(AggregateMetadata aggregate)
+    public void onAggregateDropped(final AggregateMetadata aggregate)
     {
         // NOOP
     }
 
+    /**
+     * On aggregate updated.
```
Comment (itskarlsson) [inline core/src/main/java/com/ericsson/bss/cassandra/ecchronos/core/repair/DefaultRepairConfigurationProvider.java:344]: Called when aggregate is updated

File: core/src/main/java/com/ericsson/bss/cassandra/ecchronos/core/repair/DefaultRepairConfigurationProvider.java [hunk 23]
```diff
@@ -181,100 +218,170 @@ private void updateConfiguration(TableReference tableReference, TableMetadata ta
...
+     */
     @Override
-    public void onAggregateUpdated(AggregateMetadata current, AggregateMetadata previous)
+    public void onAggregateUpdated(final AggregateMetadata current, final AggregateMetadata previous)
     {
         // NOOP
     }
 
+    /**
+     * On view created.
```
Comment (itskarlsson) [inline core/src/main/java/com/ericsson/bss/cassandra/ecchronos/core/repair/DefaultRepairConfigurationProvider.java:356]: Called when view is created

File: core/src/main/java/com/ericsson/bss/cassandra/ecchronos/core/repair/DefaultRepairConfigurationProvider.java [hunk 24]
```diff
@@ -181,100 +218,170 @@ private void updateConfiguration(TableReference tableReference, TableMetadata ta
...
+     */
     @Override
-    public void onViewCreated(ViewMetadata view)
+    public void onViewCreated(final ViewMetadata view)
     {
         // NOOP
     }
 
+    /**
+     * On view dropped.
```
Comment (itskarlsson) [inline core/src/main/java/com/ericsson/bss/cassandra/ecchronos/core/repair/DefaultRepairConfigurationProvider.java:367]: Called when view is dropped

File: core/src/main/java/com/ericsson/bss/cassandra/ecchronos/core/repair/DefaultRepairConfigurationProvider.java [hunk 25]
```diff
@@ -181,100 +218,170 @@ private void updateConfiguration(TableReference tableReference, TableMetadata ta
...
+     */
     @Override
-    public void onViewDropped(ViewMetadata view)
+    public void onViewDropped(final ViewMetadata view)
     {
         // NOOP
     }
 
+    /**
+     * On view updated.
```
Comment (itskarlsson) [inline core/src/main/java/com/ericsson/bss/cassandra/ecchronos/core/repair/DefaultRepairConfigurationProvider.java:378]: Called when view is updated

File: core/src/main/java/com/ericsson/bss/cassandra/ecchronos/core/repair/ScheduledRepairJobView.java [hunk 26]
```diff
@@ -49,48 +54,94 @@ public ScheduledRepairJobView(UUID id, TableReference tableReference, RepairConf
...
+     *
+     * @return double
+     */
     public double getProgress()
     {
         return myProgress;
     }
 
+    /**
+     * Get net repair.
```
Comment (itskarlsson) [inline core/src/main/java/com/ericsson/bss/cassandra/ecchronos/core/repair/ScheduledRepairJobView.java:118]: next

File: core/src/main/java/com/ericsson/bss/cassandra/ecchronos/core/repair/state/RepairStateFactoryImpl.java [hunk 27]
```diff
@@ -66,30 +67,55 @@ public static Builder builder()
         private RepairHistoryProvider myRepairHistoryProvider;
         private TableRepairMetrics myTableRepairMetrics;
 
-        public Builder withReplicationState(ReplicationState replicationState)
+        /**
+         * Build repair state with replication state.
```
Comment (itskarlsson) [inline core/src/main/java/com/ericsson/bss/cassandra/ecchronos/core/repair/state/RepairStateFactoryImpl.java:71]: repair state factory

File: core/src/main/java/com/ericsson/bss/cassandra/ecchronos/core/repair/state/RepairStateFactoryImpl.java [hunk 28]
```diff
@@ -66,30 +67,55 @@ public static Builder builder()
...
+         */
+        public Builder withReplicationState(final ReplicationState replicationState)
         {
             myReplicationState = replicationState;
             return this;
         }
 
-        public Builder withHostStates(HostStates hostStates)
+        /**
+         * Build repair state with host states.
```
Comment (itskarlsson) [inline core/src/main/java/com/ericsson/bss/cassandra/ecchronos/core/repair/state/RepairStateFactoryImpl.java:82]: repair state factory

File: core/src/main/java/com/ericsson/bss/cassandra/ecchronos/core/repair/state/RepairStateFactoryImpl.java [hunk 29]
```diff
@@ -66,30 +67,55 @@ public static Builder builder()
...
+         */
+        public Builder withHostStates(final HostStates hostStates)
         {
             myHostStates = hostStates;
             return this;
         }
 
-        public Builder withRepairHistoryProvider(RepairHistoryProvider repairHistoryProvider)
+        /**
+         * Build repair state with repair history provider.
```
Comment (itskarlsson) [inline core/src/main/java/com/ericsson/bss/cassandra/ecchronos/core/repair/state/RepairStateFactoryImpl.java:93]: repair state factory

File: core/src/main/java/com/ericsson/bss/cassandra/ecchronos/core/repair/state/RepairStateFactoryImpl.java [hunk 30]
```diff
@@ -66,30 +67,55 @@ public static Builder builder()
...
+         */
+        public Builder withRepairHistoryProvider(final RepairHistoryProvider repairHistoryProvider)
         {
             myRepairHistoryProvider = repairHistoryProvider;
             return this;
         }
 
-        public Builder withTableRepairMetrics(TableRepairMetrics tableRepairMetrics)
+        /**
+         * Build repair state with table repair metrics.
```
Comment (itskarlsson) [inline core/src/main/java/com/ericsson/bss/cassandra/ecchronos/core/repair/state/RepairStateFactoryImpl.java:104]: repair state factory

File: core/src/main/java/com/ericsson/bss/cassandra/ecchronos/core/repair/state/RepairStateFactoryImpl.java [hunk 31]
```diff
@@ -66,30 +67,55 @@ public static Builder builder()
...
+         * @return Builder
+         */
+        public Builder withTableRepairMetrics(final TableRepairMetrics tableRepairMetrics)
         {
             myTableRepairMetrics = tableRepairMetrics;
             return this;
         }
 
+        /**
+         * Build repair state.
```
Comment (itskarlsson) [inline core/src/main/java/com/ericsson/bss/cassandra/ecchronos/core/repair/state/RepairStateFactoryImpl.java:115]: repair state factory

**Review by tommystendahl — APPROVED** [review]

File: core/src/main/java/com/ericsson/bss/cassandra/ecchronos/core/repair/OnDemandStatus.java [hunk 32]
```diff
@@ -134,12 +139,23 @@ public OnDemandStatus(NativeConnectionProvider nativeConnectionProvider)
...
+     * @return Ongoing jobs
+     */
     public UUID getHostId()
     {
         return myHostId;
     }
 
-    public Set<OngoingJob> getOngoingJobs(ReplicationState replicationState)
+    /**
+     * Create and get ongoing jobs with a replication state.
```
Comment (masokol) [inline core/src/main/java/com/ericsson/bss/cassandra/ecchronos/core/repair/OnDemandStatus.java:153]: Still doesn't say what it does, i was more after something like:
Reads from the table X based on A, B, C and returns in form of...

This comment applies to all methods in this file.

File: core/src/main/java/com/ericsson/bss/cassandra/ecchronos/core/repair/RepairGroup.java [hunk 33]
```diff
@@ -52,22 +59,38 @@ public class RepairGroup extends ScheduledTask
...
+                .checkNotNull(builder.repairPolicies, "Repair policies must be set"));
+        myRepairHistory = Preconditions
+                .checkNotNull(builder.repairHistory, "Repair history must be set");
+        myJobId = Preconditions
+                .checkNotNull(builder.jobId, "Job id must be set");
     }
 
+    /**
+     * Execute repair job.
+     *
```
Comment (masokol) [inline core/src/main/java/com/ericsson/bss/cassandra/ecchronos/core/repair/RepairGroup.java:91]: This javadoc needs more info. Something like:
Executes the repair tasks this repairGroup is responsible for. Repair tasks can succeeded or fail, repair tasks blocked by run policy are counted as failed.

File: core/src/main/java/com/ericsson/bss/cassandra/ecchronos/core/repair/RepairGroup.java [hunk 34]
```diff
@@ -113,8 +137,16 @@ private boolean shouldContinue()
         return myRepairPolicies.stream().allMatch(repairPolicy -> repairPolicy.shouldRun(myTableReference));
     }
 
+    /**
+     * Get lock.
+     *
```
[the remark this answers is not in the document]
Comment (masokol) [reply core/src/main/java/com/ericsson/bss/cassandra/ecchronos/core/repair/RepairGroup.java:141]: Still not fixed.

File: core/src/main/java/com/ericsson/bss/cassandra/ecchronos/core/repair/ScheduledRepairJobView.java [hunk 35]
```diff
@@ -49,48 +54,94 @@ public ScheduledRepairJobView(UUID id, TableReference tableReference, RepairConf
...
+     *
+     * @return long
+     */
     public long getCompletionTime()
     {
         return myCompletionTime;
     }
 
+    /**
+     * Equality.
```
Comment (masokol) [inline core/src/main/java/com/ericsson/bss/cassandra/ecchronos/core/repair/ScheduledRepairJobView.java:138]: Might be worth to include what variables are considered here, since not all are.

File: core/src/main/java/com/ericsson/bss/cassandra/ecchronos/core/repair/state/RepairHistoryProviderImpl.java [hunk 36]
```diff
@@ -89,16 +93,37 @@ public RepairHistoryProviderImpl(NodeResolver nodeResolver, CqlSession session,
         myClock = clock;
     }
 
+    /**
+     * Iterating over repair history in a table, based on time and filters.
```
Comment (masokol) [inline core/src/main/java/com/ericsson/bss/cassandra/ecchronos/core/repair/state/RepairHistoryProviderImpl.java:97]: be more specific, "based on time" doesn't say anything. Maybe mention from-to and how these values are derived.

File: core/src/main/java/com/ericsson/bss/cassandra/ecchronos/core/repair/state/RepairHistoryProviderImpl.java [hunk 37]
```diff
@@ -89,16 +93,37 @@ public RepairHistoryProviderImpl(NodeResolver nodeResolver, CqlSession session,
...
+    public Iterator<RepairEntry> iterate(final TableReference tableReference,
+                                         final long to,
+                                         final Predicate<RepairEntry> predicate)
     {
         long from = myClock.millis() - myLookbackTime;
         return iterate(tableReference, to, from, predicate);
     }
 
+    /**
+     * Iterating over repair history in a table, based on time and filters.
```
Comment (masokol) [inline core/src/main/java/com/ericsson/bss/cassandra/ecchronos/core/repair/state/RepairHistoryProviderImpl.java:114]: same as above

File: core/src/main/java/com/ericsson/bss/cassandra/ecchronos/core/repair/state/RepairHistoryProviderImpl.java [hunk 38]
```diff
@@ -114,14 +139,27 @@ public Iterator<RepairEntry> iterate(TableReference tableReference, long to, lon
         return new RepairEntryIterator(resultSet.iterator(), predicate);
     }
 
+    /**
+     * Iterating over repair history in a table, based on time and filters.
```
Comment (masokol) [inline core/src/main/java/com/ericsson/bss/cassandra/ecchronos/core/repair/state/RepairHistoryProviderImpl.java:143]: same as above

File: core/src/main/java/com/ericsson/bss/cassandra/ecchronos/core/repair/state/RepairStateImpl.java [hunk 39]
```diff
@@ -209,14 +233,20 @@ private boolean replicasAreRepairable(VnodeRepairState vnodeRepairState)
         return true;
     }
 
+    /**
```
[the remark this answers is not in the document]
Comment (masokol) [reply core/src/main/java/com/ericsson/bss/cassandra/ecchronos/core/repair/state/RepairStateImpl.java:236]: Explain in javadoc how this is decided.

File: core/src/main/java/com/ericsson/bss/cassandra/ecchronos/core/repair/state/VnodeRepairStateFactoryImpl.java [hunk 40]
```diff
@@ -39,17 +39,27 @@ public class VnodeRepairStateFactoryImpl implements VnodeRepairStateFactory
...
+                                       final RepairHistoryProvider repairHistoryProvider,
+                                       final boolean toUseSubRanges)
     {
         myReplicationState = replicationState;
         myRepairHistoryProvider = repairHistoryProvider;
-        this.useSubRanges = useSubRanges;
+        this.useSubRanges = toUseSubRanges;
     }
 
+    /**
```
[the remark this answers is not in the document]
Comment (masokol) [reply core/src/main/java/com/ericsson/bss/cassandra/ecchronos/core/repair/state/VnodeRepairStateFactoryImpl.java:51]: Explain in javadoc how this is done.

File: core/src/main/java/com/ericsson/bss/cassandra/ecchronos/core/repair/state/VnodeRepairStateFactoryImpl.java [hunk 41]
```diff
@@ -58,38 +68,63 @@ public VnodeRepairStates calculateNewState(TableReference tableReference, Repair
...
+            LOG.debug("Table {} last repaired at {}, iterating repair entries until that time",
+                    tableReference, lastRepairedAt);
+            repairEntryIterator = myRepairHistoryProvider.iterate(tableReference,
+                    now, lastRepairedAt, (repairEntry) -> acceptRepairEntries(repairEntry, tokenRangeToReplicaMap));
         }
 
         return generateVnodeRepairStates(lastRepairedAt, previous, repairEntryIterator, tokenRangeToReplicaMap);
     }
 
+    /**
```
[the remark this answers is not in the document]
Comment (masokol) [reply core/src/main/java/com/ericsson/bss/cassandra/ecchronos/core/repair/state/VnodeRepairStateFactoryImpl.java:85]: same as above

File: core/src/main/java/com/ericsson/bss/cassandra/ecchronos/core/utils/ReplicatedTableProviderImpl.java [hunk 42]
```diff
@@ -57,8 +60,14 @@ public ReplicatedTableProviderImpl(Node node, CqlSession session, TableReference
                 .collect(Collectors.toSet());
     }
 
+    /**
```
[the remark this answers is not in the document]
Comment (masokol) [reply core/src/main/java/com/ericsson/bss/cassandra/ecchronos/core/utils/ReplicatedTableProviderImpl.java:63]: Explain in javadoc what "supported" means

File: core/src/main/java/com/ericsson/bss/cassandra/ecchronos/core/repair/OnDemandStatus.java [hunk 43]
```diff
@@ -134,12 +139,23 @@ public OnDemandStatus(NativeConnectionProvider nativeConnectionProvider)
...
+     * @return Ongoing jobs
+     */
     public UUID getHostId()
     {
         return myHostId;
     }
 
-    public Set<OngoingJob> getOngoingJobs(ReplicationState replicationState)
+    /**
+     * Get all jobs for the host that have the status 'started' and add them to ongoing jobs.
```
Comment (masokol) [inline core/src/main/java/com/ericsson/bss/cassandra/ecchronos/core/repair/OnDemandStatus.java:153]: this host

Comment (masokol) [inline core/src/main/java/com/ericsson/bss/cassandra/ecchronos/core/repair/OnDemandStatus.java:153]: this is not needed "and add them..."

File: core/src/main/java/com/ericsson/bss/cassandra/ecchronos/core/repair/OnDemandStatus.java [hunk 44]
```diff
@@ -167,6 +183,11 @@ public Set<OngoingJob> getOngoingJobs(ReplicationState replicationState)
         return ongoingJobs;
     }
 
+    /**
+     * Add jobs for all nodes and their token ranges to ongoing jobs and return them.
```
Comment (masokol) [inline core/src/main/java/com/ericsson/bss/cassandra/ecchronos/core/repair/OnDemandStatus.java:187]: Get jobs for all nodes independent of their status.

File: core/src/main/java/com/ericsson/bss/cassandra/ecchronos/core/repair/OnDemandStatus.java [hunk 45]
```diff
@@ -181,12 +202,18 @@ public Set<OngoingJob> getAllClusterWideJobs()
         return ongoingJobs;
     }
 
-    public Set<OngoingJob> getAllJobs(ReplicationState replicationState)
+    /**
+     * Add jobs for the local node and its token ranges to ongoing jobs and return them.
```
Comment (masokol) [inline core/src/main/java/com/ericsson/bss/cassandra/ecchronos/core/repair/OnDemandStatus.java:206]: Get all jobs for this host independent of their status.

File: core/src/main/java/com/ericsson/bss/cassandra/ecchronos/core/repair/OnDemandStatus.java [hunk 46]
```diff
@@ -267,33 +316,70 @@ public void addNewJob(UUID host, UUID jobId, TableReference tableReference, int
...
+    public void finishJob(final UUID jobId)
     {
-        mySession.execute(myUpdateJobToFinishedStatement.bind(Instant.ofEpochMilli(System.currentTimeMillis()), myHostId, jobId));
+        mySession.execute(myUpdateJobToFinishedStatement.bind(Instant.ofEpochMilli(System.currentTimeMillis()),
+                myHostId, jobId));
     }
 
-    public void failJob(UUID jobId)
+    /**
+     * Update a failed job with current time stamp.
```
Comment (masokol) [inline core/src/main/java/com/ericsson/bss/cassandra/ecchronos/core/repair/OnDemandStatus.java:342]: Update a job to failed status with current timestamp

File: core/src/main/java/com/ericsson/bss/cassandra/ecchronos/core/repair/OnDemandStatus.java [hunk 47]
```diff
@@ -203,7 +203,7 @@ public Set<OngoingJob> getAllClusterWideJobs()
     }
 
     /**
-     * Add jobs for the local node and its token ranges to ongoing jobs and return them.
+     * Get jobs for all the nodes, independent of their status.
      *
```
Comment (masokol) [inline core/src/main/java/com/ericsson/bss/cassandra/ecchronos/core/repair/OnDemandStatus.java:207]: this host

**Review by masokol — COMMENTED** [review]
There are more review comments that i left a few days ago.

**Review by masokol — COMMENTED** [review]
LGTM
